---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: group-mariadb-operators-placement-binding
  namespace: rhacm-policies
placementRef:
  name: dev-clusters
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-group-mariadb-operators 
  kind: Policy
  apiGroup: policy.open-cluster-management.io
